// Code generated by "stringer -type=Type type.go"; DO NOT EDIT

package msg

import "fmt"

const _Type_name = "ILLEGALINITWAIT_CHATWAIT_MAGICCHATMAGICEFFECTDUALOVER"

var _Type_index = [...]uint8{0, 7, 11, 20, 30, 34, 39, 45, 53}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
